sonar.projectKey=viratvasu0_webapp
sonar.projectName=webapp
sonar.projectVersion=1.0.0

###########################################################
# Source Layout Structure
###########################################################

# No source code folders found at root. Needs manual review by Devs.
sonar.sources=.
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts,**/test/**/*.js

###########################################################
# Enterprise Analysis Exclusions
###########################################################

sonar.exclusions=**/*.d.ts,**/build/**,**/built/**
sonar.coverage.exclusions=**/*.spec.ts,**/*.test.ts,src/app/mocks/****,src/environments/*,src/test.ts
sonar.cpd.exclusions=**/*.generated.*,**/generated/**,**/*.test.ts,**/*.spec.ts

###########################################################
# SCM Tracking Control
###########################################################

sonar.scm.provider=git
sonar.scm.forceReloadAll=true

###########################################################
# Platform Quality Gates Config
###########################################################

sonar.qualitygate.wait=true
sonar.qualitygate.timeout=1800
